name: C++ Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run all tests
        run: |
          for test_bin in build/tests/TEST_*; do
            echo "Running $test_bin"
            "$test_bin"
          done